version: "3.4"
services:
  ersatztv:
    container_name: ersatztv
    image: jasongdove/ersatztv:latest-nvidia
    environment:
      - TZ=${TZ}
    volumes:
      - '${CONFIG}:/root/.local/share/ersatztv'
      - '${STORAGE}:${STORAGE}:ro'
    ports:
      - 8409:8409
    restart: unless-stopped
