version: "3.4"
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIGS}:/app/data/configs
      - ${ICONS}:/app/data/icons
    restart: unless-stopped
    privileged: true
    ports:
      - 5005:7575