version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    environment:
      - TZ=${TZ}
      - "DNS=1.1.1.1"
    volumes:
      - /dev/net:/dev/net:z
      - /dev/net/tun:/dev/net/tun
      - ${CONFIG}/vpn:/vpn
    ports:
      - 9696:9696 # Prowlarr
      - 6767:6767 # Bazarr
      - 8113:8113 # Qbittorrent
    restart: unless-stopped
    cap_add:
      - net_admin
    security_opt:
      - label:disable

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=${THEMEPKG}:prowlarr
      - TP_THEME=${THEMENAME}
    volumes:
      - ${CONFIG}/prowlarr:/config
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - "vpn"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:amd64-latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=${THEMEPKG}:sonarr
      - TP_THEME=${THEMENAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/sonarr:/config
      - ${STORAGE}:/storage
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:amd64-latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=${THEMEPKG}:radarr
      - TP_THEME=${THEMENAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/radarr:/config
      - ${STORAGE}:/storage
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=${THEMEPKG}:bazarr
      - TP_THEME=${THEMENAME}
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${STORAGE}:/storage
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - "vpn"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8113
    volumes:
      - ${CONFIG}/qbittorrent:/config
      - ${STORAGE}:/storage
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - "vpn"

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${CONFIG}/deluge:/config
      - ${STORAGE}:/storage
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8112:8112
      - 58846:58846
    restart: unless-stopped
