version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - ${CONFIG}/redis:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ${CONFIG}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless 
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8942:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${CONFIG}/paperless/data:/usr/src/paperless/data
      - ${CONFIG}/paperless/media:/usr/src/paperless/media
      - ${CONFIG}/export:/usr/src/paperless/export
      - ${CONFIG}/consume:/usr/src/paperless/consume
    environment:
      - USERMAP_UID=${PUID}
      - USERMAP_GID=${PGID}
      - PAPERLESS_URL=${HOSTNAME}
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped