version: "3.4"
services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    volumes:
      - ${CONFIG}:/config
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - OOKLA_EULA_GDPR=true
      - BASE_PATH=/speed
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    ports:
      - 8765:80
